# Generated by Django 3.2.2 on 2021-06-11 09:46

from django.db import migrations
from django.conf import settings

def make_preferences(apps, schema_editor):

    User = apps.get_model(settings.AUTH_USER_MODEL)
    Preferences = apps.get_model('users', 'Preferences')
    preferencess = [Preferences(user=user) for user in User.objects.filter(preferences=None)]
    Preferences.objects.bulk_create(preferencess)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210611_1145'),
    ]

    operations = [
        migrations.RunPython(make_preferences),
    ]
