# Generated by Django 3.2.4 on 2021-06-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('requested', 'Requested, but not approved by approver.'), ('approved', 'Approved by approver.'), ('ordered', 'Order is placed.'), ('notapproved', 'Order is not approved.'), ('finished', 'Order is finished.'), ('canceled', 'Order has been canceled.')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('requested', 'Requested, but not approved by approver.'), ('approved', 'Approved by approver.'), ('ordered', 'Order is placed.'), ('notapproved', 'Order is not approved.'), ('finished', 'Order is finished.'), ('canceled', 'Order has been canceled.')]),
        ),
    ]
