# Generated by Django 3.2.4 on 2021-06-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210627_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Requested'), (2, 'Approved'), (3, 'Ordered'), (4, 'Not approved'), (5, 'Finished'), (6, 'Canceled')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Requested'), (2, 'Approved'), (3, 'Ordered'), (4, 'Not approved'), (5, 'Finished'), (6, 'Canceled')], default=1),
        ),
    ]
