# Generated by Django 3.1.3 on 2020-11-23 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='next_service_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='warranty_expiration',
        ),
    ]
