# Generated by Django 3.1.3 on 2021-01-05 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Please verify that no such category already exists.', max_length=100),
        ),
        migrations.AlterField(
            model_name='flag',
            name='icon',
            field=models.CharField(default='bug', help_text='Set a icon from <a target="_blank" href="https://fontawesome.com/icons?m=free">this library</a>.', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='name',
            field=models.CharField(help_text='Please verify that no such category already exists.', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalflag',
            name='icon',
            field=models.CharField(default='bug', help_text='Set a icon from <a target="_blank" href="https://fontawesome.com/icons?m=free">this library</a>.', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, default='uncategorized', help_text='New categories can be added in Admin/Manage/Categories.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ems.category'),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='image',
            field=models.TextField(blank=True, default='default.png', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='image2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='storage_location',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', help_text='New storage locations can be added in Admin/Manage/Storage Locations.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ems.cabinet'),
        ),
        migrations.AlterField(
            model_name='historicalitemlog',
            name='file1_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalitemlog',
            name='file2_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicallab',
            name='manager',
            field=models.ForeignKey(blank=True, db_constraint=False, default=2, limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicallab',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='uncategorized', help_text='New categories can be added in Admin/Manage/Categories.', on_delete=django.db.models.deletion.SET_DEFAULT, to='ems.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='item_pics'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='item_pics'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='storage_location',
            field=models.ForeignKey(blank=True, default='', help_text='New storage locations can be added in Admin/Manage/Storage Locations.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.cabinet'),
        ),
        migrations.AlterField(
            model_name='itemlog',
            name='file1_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemlog',
            name='file2_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='manager',
            field=models.ForeignKey(blank=True, default=2, limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lab',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
