# Generated by Django 3.1.3 on 2020-12-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='object_id',
        ),
    ]
