# Generated by Django 3.1.3 on 2021-01-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_auto_20210105_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallab',
            name='manager',
            field=models.CharField(default='undefined', max_length=100),
        ),
        migrations.AlterField(
            model_name='lab',
            name='manager',
            field=models.CharField(default='undefined', max_length=100),
        ),
    ]
