# Generated by Django 3.1.3 on 2020-11-23 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ems', '0002_setup_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.flag'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='uncategorized', on_delete=django.db.models.deletion.SET_DEFAULT, to='ems.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchased_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaseduser', to=settings.AUTH_USER_MODEL),
        ),
    ]
