# Generated by Django 3.1.3 on 2020-11-24 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ems', '0002_auto_20201123_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateduser', to=settings.AUTH_USER_MODEL),
        ),
    ]
