# Generated by Django 3.1.3 on 2020-11-24 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ems', '0003_item_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added_by',
            field=models.ForeignKey(limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addeduser', to=settings.AUTH_USER_MODEL),
        ),
    ]
