# Generated by Django 3.1.3 on 2021-01-05 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ems', '0003_auto_20210105_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallab',
            name='manager',
            field=models.ForeignKey(blank=True, db_constraint=False, default=2, limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lab',
            name='manager',
            field=models.ForeignKey(blank=True, default=2, limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
