# Generated by Django 3.1.3 on 2020-11-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_auto_20201123_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_inuse',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_return',
            field=models.DateField(blank=True, null=True),
        ),
    ]
