# Generated by Django 3.1.3 on 2020-12-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_auto_20201206_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
    ]
