# Generated by Django 3.1.3 on 2020-12-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0004_auto_20201208_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalitemlog',
            old_name='file1_name',
            new_name='file1name',
        ),
        migrations.RenameField(
            model_name='itemlog',
            old_name='file1_name',
            new_name='file1name',
        ),
    ]
