# Generated by Django 3.1.3 on 2020-11-24 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ems', '0004_auto_20201124_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='purchased_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaseduser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_by',
            field=models.ForeignKey(limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateduser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='setup',
            name='manager',
            field=models.ForeignKey(blank=True, default='undefined', limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
