# Generated by Django 3.1.3 on 2021-01-11 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ems', '0004_auto_20210105_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='date_return',
            field=models.DateField(blank=True, help_text='Optional, but recommended.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='storage_location',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', help_text='New storage locations can be added in Admin/Manage/Locations.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ems.cabinet'),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optional, only the location is mandatory.', limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_return',
            field=models.DateField(blank=True, help_text='Optional, but recommended.', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='storage_location',
            field=models.ForeignKey(blank=True, default='', help_text='New storage locations can be added in Admin/Manage/Locations.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.cabinet'),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optional, only the location is mandatory.', limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
