# Generated by Django 3.1.3 on 2020-12-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0005_auto_20201206_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='image2',
            field=models.TextField(default='default.png', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalitemlog',
            name='file1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalitemlog',
            name='file2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(default='default.png', upload_to='item_pics'),
        ),
        migrations.AddField(
            model_name='itemlog',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='itemlog',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
