# Generated by Django 3.1.3 on 2021-01-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0005_auto_20210111_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='flag_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='flag_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
