# Generated by Django 3.1.3 on 2020-12-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0006_auto_20201208_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='image2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='item_pics'),
        ),
    ]
