# Generated by Django 3.1.3 on 2021-01-14 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ems', '0006_auto_20210114_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cabinet_pics'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='main_content',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='nickname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Cabinet owner is person whose stuff is stored in it.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcabinet',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcabinet',
            name='main_content',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalcabinet',
            name='nickname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalcabinet',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Cabinet owner is person whose stuff is stored in it.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='title',
            field=models.CharField(blank=True, help_text="Add short title that describes the item. E.g. 'Multimeter 0-1000V'.", max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='historicallab',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsetup',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, help_text="Add short title that describes the item. E.g. 'Multimeter 0-1000V'.", max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lab_pics'),
        ),
        migrations.AddField(
            model_name='setup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='setup_pics'),
        ),
    ]
