# Generated by Django 3.1.3 on 2020-11-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0006_auto_20201124_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qrid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
