# Generated by Django 3.1.3 on 2020-11-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0007_item_qrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='icon',
            field=models.CharField(default='bug', max_length=100),
        ),
    ]
