# Generated by Django 3.1.3 on 2020-12-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0007_auto_20201209_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='image',
            field=models.TextField(blank=True, default='default.png', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='item_pics'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
