# Generated by Django 3.1.3 on 2021-01-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0007_auto_20210114_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='tracking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tracking',
            field=models.BooleanField(default=True),
        ),
    ]
