# Generated by Django 3.1.3 on 2021-01-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0008_auto_20210118_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='qridcheck',
            field=models.CharField(blank=True, default='20210118150356', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='qridcheck',
            field=models.CharField(blank=True, default='20210118150356', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='tracking',
            field=models.BooleanField(default=True, help_text='Tracking allows for assigning an item to a user and location, common items such as multimeters are not tracked.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tracking',
            field=models.BooleanField(default=True, help_text='Tracking allows for assigning an item to a user and location, common items such as multimeters are not tracked.'),
        ),
    ]
