# Generated by Django 3.1.3 on 2021-01-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0012_auto_20210118_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitem',
            name='qridcheck',
        ),
        migrations.RemoveField(
            model_name='item',
            name='qridcheck',
        ),
    ]
