# Generated by Django 3.1.3 on 2021-01-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0014_auto_20210118_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalitem',
            old_name='qridcheck',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='qridcheck',
            new_name='version',
        ),
    ]
