# Generated by Django 3.1.3 on 2021-01-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0015_auto_20210119_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='labelstatus',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='labelstatus',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
