# Generated by Django 3.1.3 on 2021-01-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0016_auto_20210119_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='parts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='parts',
            field=models.IntegerField(default=1),
        ),
    ]
