# Generated by Django 3.1.3 on 2021-03-23 08:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0017_auto_20210126_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', help_text='New categories can be added in Admin/Manage/Categories.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ems.category'),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='description',
            field=models.TextField(help_text='Add as many terms printed on the item and possible search terms.'),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='model',
            field=models.CharField(help_text='If multiple parts (e.g. proprietary power supply) with multiple models, comma separate models.', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='parts',
            field=models.PositiveIntegerField(default=1, help_text='Number of separate parts, e.g. when an item has a proprietary power supply.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='serial',
            field=models.CharField(blank=True, help_text='Comma separate multiple serial numbers.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='title',
            field=models.CharField(default=None, help_text="Add short title that describes the item. E.g. 'Multimeter 0-1000V'.", max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, default='', help_text='New categories can be added in Admin/Manage/Categories.', on_delete=django.db.models.deletion.SET_DEFAULT, to='ems.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(help_text='Add as many terms printed on the item and possible search terms.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='model',
            field=models.CharField(help_text='If multiple parts (e.g. proprietary power supply) with multiple models, comma separate models.', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='parts',
            field=models.PositiveIntegerField(default=1, help_text='Number of separate parts, e.g. when an item has a proprietary power supply.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial',
            field=models.CharField(blank=True, help_text='Comma separate multiple serial numbers.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(default='', help_text="Add short title that describes the item. E.g. 'Multimeter 0-1000V'.", max_length=25),
            preserve_default=False,
        ),
    ]
